services:
  postgres:
    image: postgres:16-alpine
    container_name: printqueue-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: printqueue
    ports:
      - "5433:5432"
    volumes:
      - printqueue_data:/var/lib/postgresql/data

volumes:
  printqueue_data:
